DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS classrooms;
DROP TABLE IF EXISTS passed_courses;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS streams;